import { Product, FAQ, Testimonial, Category } from "@/store";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Aether Wireless Buds",
    price: 149,
    originalPrice: 199,
    category: "Audio",
    tag: "BEST SELLER",
    description: "Studio-grade audio. Zero compromise.",
    longDescription: "Experience 40 hours of playtime, active noise cancellation, and crystal-clear calls. Designed for those who refuse to settle.",
    image: "🎧",
    rating: 4.9,
    reviews: 2847,
    inStock: true,
    colors: ["#111", "#f5f5f0", "#e8ff47"],
  },
  {
    id: 2,
    name: "Nomad Mechanical Keyboard",
    price: 289,
    category: "Computing",
    tag: "NEW",
    description: "Every keystroke, a statement.",
    longDescription: "Hot-swappable switches, aluminum frame, per-key RGB. The keyboard that makes you want to type more.",
    image: "⌨️",
    rating: 4.8,
    reviews: 1203,
    inStock: true,
    colors: ["#111", "#222", "#c8df2a"],
  },
  {
    id: 3,
    name: "Zenith Desk Lamp",
    price: 119,
    originalPrice: 149,
    category: "Workspace",
    description: "Light that thinks with you.",
    longDescription: "Adaptive brightness, circadian rhythm sync, and wireless charging built right into the base. Your desk deserves better.",
    image: "💡",
    rating: 4.7,
    reviews: 986,
    inStock: true,
    colors: ["#f5f5f0", "#111"],
  },
  {
    id: 4,
    name: "Phantom Smart Watch",
    price: 399,
    category: "Wearables",
    tag: "HOT",
    description: "Your health. Quantified.",
    longDescription: "18-day battery, ECG monitoring, sleep tracking, and a display so sharp you'll forget it's a watch.",
    image: "⌚",
    rating: 4.9,
    reviews: 4521,
    inStock: true,
    colors: ["#111", "#888", "#e8ff47"],
  },
  {
    id: 5,
    name: "Lumen Portable Monitor",
    price: 329,
    category: "Computing",
    description: "Your second screen, everywhere.",
    longDescription: "4K resolution, USB-C single cable, 1ms response time. Work from anywhere without compromise.",
    image: "🖥️",
    rating: 4.6,
    reviews: 672,
    inStock: false,
    colors: ["#111", "#1a1a1a"],
  },
  {
    id: 6,
    name: "Clarity Webcam Pro",
    price: 199,
    originalPrice: 249,
    category: "Computing",
    tag: "SALE",
    description: "Look as sharp as you think.",
    longDescription: "4K 60fps, built-in ring light, AI background blur. Because first impressions matter on screen too.",
    image: "📹",
    rating: 4.8,
    reviews: 1847,
    inStock: true,
    colors: ["#111", "#333"],
  },
];

export const CATEGORIES: Category[] = [
  { id: 1, name: "Audio", count: 24, icon: "🎧", gradient: "from-purple-900/40 to-purple-900/10" },
  { id: 2, name: "Computing", count: 38, icon: "💻", gradient: "from-blue-900/40 to-blue-900/10" },
  { id: 3, name: "Workspace", count: 19, icon: "🖥️", gradient: "from-green-900/40 to-green-900/10" },
  { id: 4, name: "Wearables", count: 15, icon: "⌚", gradient: "from-orange-900/40 to-orange-900/10" },
];

export const FAQS: FAQ[] = [
  {
    id: 1,
    question: "What is FlowCart's return policy?",
    answer: "We offer a 30-day hassle-free return policy on all products. Items must be in their original condition and packaging. Once we receive your return, refunds are processed within 3-5 business days.",
  },
  {
    id: 2,
    question: "How long does shipping take?",
    answer: "Standard shipping takes 3-7 business days. Express shipping (1-2 days) is available at checkout. Orders over $150 qualify for free standard shipping automatically.",
  },
  {
    id: 3,
    question: "Are all products covered by warranty?",
    answer: "Yes. Every product on FlowCart comes with a minimum 1-year manufacturer warranty. Premium products and select categories come with extended 2-3 year coverage.",
  },
  {
    id: 4,
    question: "Do you offer international shipping?",
    answer: "We currently ship to 48 countries. Shipping costs and delivery times vary by destination. Import duties and taxes may apply and are the responsibility of the buyer.",
  },
  {
    id: 5,
    question: "How do I track my order?",
    answer: "Once your order ships, you'll receive a confirmation email with your tracking number. You can track your order in real-time through your account dashboard or the carrier's website.",
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Sarah Chen",
    role: "Product Designer at Linear",
    avatar: "SC",
    content: "FlowCart has completely changed how I kit out my workspace. The curation is impeccable — every product actually delivers on its promise.",
    rating: 5,
  },
  {
    id: 2,
    name: "Marcus Webb",
    role: "Senior Engineer, Vercel",
    avatar: "MW",
    content: "The Nomad keyboard was a game-changer. Finally a platform that understands what quality hardware actually means. Fast shipping too.",
    rating: 5,
  },
  {
    id: 3,
    name: "Priya Nair",
    role: "Founder, Minimalist Studio",
    avatar: "PN",
    content: "I've bought from three different premium tech stores. FlowCart is the only one where I've never had a bad experience. Return policy is genuinely no-fuss.",
    rating: 5,
  },
];

export const CHART_DATA = [
  { month: "Jan", revenue: 42000, orders: 380 },
  { month: "Feb", revenue: 51000, orders: 420 },
  { month: "Mar", revenue: 47000, orders: 395 },
  { month: "Apr", revenue: 63000, orders: 540 },
  { month: "May", revenue: 79000, orders: 680 },
  { month: "Jun", revenue: 91000, orders: 790 },
  { month: "Jul", revenue: 88000, orders: 750 },
  { month: "Aug", revenue: 102000, orders: 890 },
  { month: "Sep", revenue: 97000, orders: 840 },
  { month: "Oct", revenue: 118000, orders: 1020 },
  { month: "Nov", revenue: 143000, orders: 1240 },
  { month: "Dec", revenue: 167000, orders: 1450 },
];